language: node_js
sudo: false
node_js:
  - "4.2"
  - "5.0"
env:
  - npm_config_coverage
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - $CXX --version
  - case ${TRAVIS_NODE_VERSION} in 0.8*|0.10*) npm install -g npm@2 ;; esac
after_success:
  - bash <(curl -s https://codecov.io/bash)